# Handling Missing Data

In [66]:
import numpy as np
import pandas as pd

In [67]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [68]:
for dtype in ["object", "int"]:
    print("dtype=", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype= object
144 ms ± 24.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype= int
6.58 ms ± 641 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [69]:
print(1E8)

100000000.0

# NaN: Missing numerical data

In [70]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [71]:
1 + np.nan

nan

In [72]:
0 * np.nan

nan

In [73]:
vals2.sum(), vals2.min(), vals2.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [74]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

Nan only works with floating-point numbers so floats.
Any math involing NaN becomes Nan
ignoring NaN function --> they skip the missing value
NaN only exists for floating number so not for strings, integers etc.

### NaN and None in Pandas

In [75]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

Pandas converts None into NaN when working with numbers.

In [76]:
x = pd.Series(range(2), dtype=int)

In [77]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

None -> NaN
int64 -> float64
(type upcasting)

# Operating on Null Values

### Detecting null values

In [78]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [79]:
data[data.notnull()]

0        1
2    hello
dtype: object

isnull() → tells you where data is missing
notnull() → tells you where data exists
They return True/False for every element.

In [80]:
# Dropping null values

In [81]:
data.dropna()

0        1
2    hello
dtype: object

dropna() removes rows or columns that contain missing values (NaN / None)

In [82]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [83]:
data.dropna(inplace=True)

In [84]:
data

0        1
2    hello
dtype: object

In [85]:
data = pd.Series([10, 11, None, 13])
print(data)

0    10.0
1    11.0
2     NaN
3    13.0
dtype: float64

In [86]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2,    3,   5],
                   [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [87]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [88]:
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [89]:
df.dropna(axis="columns")

   2
0  2
1  5
2  6

In [97]:
df.dropna(axis=0)

     0    1  2
1  2.0  3.0  5

### **Filling null values**

In [91]:
data = pd.Series([1, np.nan, 2, None, 3], index=list("abcde"))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [92]:
# filling NaN values with single values like Zeros.
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [93]:
# forward-fill 
data.fillna(method="ffill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_17900\246614430.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="ffill")

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [94]:
# back-fill
data.fillna(method="bfill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_17900\3478517277.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="bfill")

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [95]:
# for DataFrames (possible of the same options)
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [96]:
df.fillna(method="ffill", axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17900\2433833841.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", axis=1)

     0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0