## Hierarchical Indexing

In [2]:
import pandas as pd
import numpy as np

In [3]:
index = [("California", 2000), ("California", 2010),
         ("New York", 2000), ("New York", 2010), 
         ("Texas", 2000), ("Texas", 2010)]

populations = [33871648, 37253956,
               1897457, 19378102,
               20851828, 25145561]

pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)       1897457
(New York, 2010)      19378102
(Texas, 2000)         20851828
(Texas, 2010)         25145561
dtype: int64

### Pandas MultiIndex

In [4]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [5]:
# Shows the State name once (better representation)
# Same Value is in the line above
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000     1897457
            2010    19378102
Texas       2000    20851828
            2010    25145561
dtype: int64

In [6]:
# Accessing all data from 2010 with Pandas slicing 
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

### MultiIndex as extra dimension

In [7]:
# Data could also be stored in a DataFrame (with columns and rows labels)
# Unstacking Method, converts multi-index Series into DataFrames
pop_df = pop.unstack()
pop_df

                2000      2010
California  33871648  37253956
New York     1897457  19378102
Texas       20851828  25145561

In [8]:
# Opposite: stack() method, converts DataFrame into multi-index Series
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000     1897457
            2010    19378102
Texas       2000    20851828
            2010    25145561
dtype: int64

In [9]:
pop_df = pd.DataFrame({"total": pop,
"under 18": [9267089, 9284094,
             4687374, 4318033,
             5906301, 6879014]})

pop_df

                    total  under 18
California 2000  33871648   9267089
           2010  37253956   9284094
New York   2000   1897457   4687374
           2010  19378102   4318033
Texas      2000  20851828   5906301
           2010  25145561   6879014

In [10]:
f_u18 = pop_df["under 18"] / pop_df["total"]
f_u18.unstack()

                2000      2010
California  0.273594  0.249211
New York    2.470345  0.222831
Texas       0.283251  0.273568

## Methods of MultiIndex Creation

In [11]:
df = pd.DataFrame(np.random.rand(4, 2),
index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
columns=["data1", "data2"])

df

        data1     data2
a 1  0.989203  0.567344
  2  0.334789  0.538763
b 1  0.870397  0.774567
  2  0.107734  0.030974

In [12]:
data = {("California", 2000): 33871648,
        ("California", 2010): 37253956,
        ("Texas", 2000): 20851820,
        ("Texas", 2010): 25145561,
        ("New York", 2000): 18976457,
        ("New York", 2010): 19378102}

pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [13]:
pd.MultiIndex.from_arrays([["a", "a", "b", "b"], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [14]:
pd.MultiIndex.from_tuples([("a", 1), ("a", 2), ("b", 1), ("b", 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [15]:
pd.MultiIndex.from_product([["a", "b"], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

### MultiIndex level names

In [16]:
pop.index.names = ["state", "year"]
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000     1897457
            2010    19378102
Texas       2000    20851828
            2010    25145561
dtype: int64

### MultiIndex for columns

In [17]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
names=["year", "visit"])

In [18]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [19]:
columns = pd.MultiIndex.from_product([["Bob", "Guido", "Sue"], ["HR", "Temp"]], names=["subject", "type"])

In [20]:
columns

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['subject', 'type'])

In [23]:
# mocking the data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

In [24]:
data

array([[32. , 35.9, 35. , 36.4, 38. , 37.6],
       [17. , 38.7, 41. , 35.7, 45. , 38.3],
       [48. , 36.9, 26. , 36.5, 43. , 37.4],
       [26. , 37.1, 45. , 35.7, 49. , 36.8]])

In [25]:
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      32.0  35.9  35.0  36.4  38.0  37.6
     2      17.0  38.7  41.0  35.7  45.0  38.3
2014 1      48.0  36.9  26.0  36.5  43.0  37.4
     2      26.0  37.1  45.0  35.7  49.0  36.8

In [26]:
health_data["Guido"]

type          HR  Temp
year visit
2013 1      35.0  36.4
     2      41.0  35.7
2014 1      26.0  36.5
     2      45.0  35.7

## Indexing and Slicing a MultiIndex

### Multiply indexed Series

In [27]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000     1897457
            2010    19378102
Texas       2000    20851828
            2010    25145561
dtype: int64

In [28]:
pop["California", 2000]

np.int64(33871648)

In [29]:
pop["California"]

year
2000    33871648
2010    37253956
dtype: int64

In [30]:
pop.loc["California":"New York"]

state       year
California  2000    33871648
            2010    37253956
New York    2000     1897457
            2010    19378102
dtype: int64

In [31]:
pop[:, 2000]

state
California    33871648
New York       1897457
Texas         20851828
dtype: int64

In [32]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [33]:
pop[["California", "Texas"]]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851828
            2010    25145561
dtype: int64

### Multiply indexed DataFrames

In [34]:
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      32.0  35.9  35.0  36.4  38.0  37.6
     2      17.0  38.7  41.0  35.7  45.0  38.3
2014 1      48.0  36.9  26.0  36.5  43.0  37.4
     2      26.0  37.1  45.0  35.7  49.0  36.8

In [35]:
health_data["Guido", "HR"]

year  visit
2013  1        35.0
      2        41.0
2014  1        26.0
      2        45.0
Name: (Guido, HR), dtype: float64

## Rearranging Multi-Indices

### Sorted and unsorted indicies

In [36]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.872732
      2      0.339634
c     1      0.599857
      2      0.322145
b     1      0.256780
      2      0.285734
dtype: float64

In [37]:
data = data.sort_index()
data

char  int
a     1      0.872732
      2      0.339634
b     1      0.256780
      2      0.285734
c     1      0.599857
      2      0.322145
dtype: float64

In [38]:
data["a":"b"]

char  int
a     1      0.872732
      2      0.339634
b     1      0.256780
      2      0.285734
dtype: float64

### Index setting and resetting

In [39]:
pop_flat = pop.reset_index(name="population")
pop_flat

        state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000     1897457
3    New York  2010    19378102
4       Texas  2000    20851828
5       Texas  2010    25145561

In [40]:
pop_flat.set_index(["state", "year"])

                 population
state      year
California 2000    33871648
           2010    37253956
New York   2000     1897457
           2010    19378102
Texas      2000    20851828
           2010    25145561

## Data Aggregations on Multi-Indices

In [41]:
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      32.0  35.9  35.0  36.4  38.0  37.6
     2      17.0  38.7  41.0  35.7  45.0  38.3
2014 1      48.0  36.9  26.0  36.5  43.0  37.4
     2      26.0  37.1  45.0  35.7  49.0  36.8

In [43]:
data_mean = health_data.groupby(by="year").mean()
data_mean

subject   Bob       Guido          Sue
type       HR  Temp    HR   Temp    HR   Temp
year
2013     24.5  37.3  38.0  36.05  41.5  37.95
2014     37.0  37.0  35.5  36.10  46.0  37.10