## Introduction to Pandas Objects

In [63]:
import numpy as np
import pandas as pd

### **The Pandas Series Object**

In [64]:
data = pd.Series([0.25, 0,5, 0.75, 1.0])
data

0    0.25
1    0.00
2    5.00
3    0.75
4    1.00
dtype: float64

In [65]:
# accessing the values
data.values

array([0.25, 0.  , 5.  , 0.75, 1.  ])

In [66]:
# the index
data.index

RangeIndex(start=0, stop=5, step=1)

In [67]:
# accessing the data with square brackets
data[1]
data[1:3]

1    0.0
2    5.0
dtype: float64

### **Series as generalized NumPy array**

In [68]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [69]:
# accessing the item
data["c"]

np.float64(0.75)

In [70]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [71]:
# accessing the item with the new assigned index
data[3]

np.float64(0.75)

### **Series as specialized dictionary**

In [72]:
population_dict = {"California": 38332521,
                   "Texas": 26448193,
                   "New York": 19651127,
                   "Florida": 19552860,
                   "Illinois": 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [73]:
# index drawn from the sorted keys
population["California"]

np.int64(38332521)

In [74]:
# Series also supports array-style operations like slicing
population["California":"Florida"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

### **Constructing Series objects**

In [75]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [76]:
pd.Series(5, index=[100, 200, 500])

100    5
200    5
500    5
dtype: int64

In [77]:
pd.Series({2:"a", 1:"b", 3:"c"})

2    a
1    b
3    c
dtype: object

In [78]:
# index can be set if needed
pd.Series({2:"a", 1:"b", 3:"c"}, index=[3, 2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

In [79]:
area_dict = {"California": 423967, "Texas": 695662, "New York": 141297, "Florida": 170312, "Illinois": 149995}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [80]:
states = pd.DataFrame({"population": population, "area": area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### **Dataframe as specializd dictionary**

In [81]:
states["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing Dataframe objects

In [82]:
pd.DataFrame(population, columns=["population"])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [83]:
# converting lists to dicts
data = [{"a": i, "b": 2 * i}
        for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [84]:
pd.DataFrame([{"a": 1, "b": 2}, {"b":3, "c": 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [85]:
# converting a dictionary to a Series of Objects
pd.DataFrame({"population": population, 
              "area": area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [86]:
# converting a two dimensional Numpy to a Series of Objects
pd.DataFrame(np.random.rand(3, 2),
             columns=["foo", "bar"],
             index = ["a", "b", "c"])

        foo       bar
a  0.081270  0.237860
b  0.949924  0.847548
c  0.816093  0.912545

In [87]:
# converting a Numpy Array to a Series of Objects
A = np.zeros(3, dtype=[("A", "i8"), ("B", "f8")])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

## The Pandas Index Object

In [88]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### **Index as immutable array**

In [89]:
ind[1]

np.int64(3)

In [90]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [91]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

### **Index as ordered set**

In [93]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB # intersection

Index([0, 3, 5, 7, 9], dtype='int64')

In [94]:
indA

Index([1, 3, 5, 7, 9], dtype='int64')

In [95]:
indB

Index([2, 3, 5, 7, 11], dtype='int64')

In [96]:
indA & indB

Index([0, 3, 5, 7, 9], dtype='int64')

## Data Indexing and Selection

### **Series as dictionary**

In [97]:
import pandas as pd

data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=["a","b","c","d"])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [98]:
"a" in data

True

In [99]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [100]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [101]:
# extending the data
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### **Series as one dimensional array**

In [102]:
# slicing by specific index
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [103]:
# masking 
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [104]:
# fancy indexing
data[["a", "e"]]

a    0.25
e    1.25
dtype: float64

### **Indexers: Ioc, iloc and ix**

In [107]:
data = pd.Series(["a", "b", "c"], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [108]:
data[1]

'a'

In [109]:
data[1:3]

3    b
5    c
dtype: object

In [119]:
data = [
    {"name": "Aditi", "age": 15, "weight": 55}, 
    {"name": "Sneha", "age": 12, "weight": 45},
    {"name": "Yuri", "age": 22, "weight": 66}
    ]
df = pd.DataFrame(data)
df

    name  age  weight
0  Aditi   15      55
1  Sneha   12      45
2   Yuri   22      66

In [121]:
df.iloc[:2, :2]

    name  age
0  Aditi   15
1  Sneha   12

In [125]:
df.loc[0:2, ["name", "weight"]]

    name  weight
0  Aditi      55
1  Sneha      45
2   Yuri      66